Nio:
当线程从通道读取数据到缓冲区时，线程依然可以做其他事情。

NIO是面向通道和缓冲区的，意思就是：数据总是从通道中读到buffer缓冲区内，或者从buffer写入到通道中。

Builder模式：比如AlertDialog.Builder
适配器模式
命 令模式
观察者模式
抽象工厂模式

比如Retrfit中有很多个Service 你完全可以用工厂模式做

Android中适配器模式
https://blog.csdn.net/u014769864/article/details/78463958
把一个类的接口转换为客户端所期待的另一种接口，从而使原本因接口不匹配而无法再一起工作的两个类能够在一起工作。
又称为：转化器模式、变压器模式或包装模式。
做法是将类自己的接口包裹在一个已存在的类中。
上面提到Android中的listview,因为不同的Listview所要呈现的视图也是不同的，为了应对这种变化，就通过一个适配器来将这种变化和我们的ListView实现一个隔离和适配。我们可以通过一个继承自BaseAdapter类来实现自己的适配器，来将我们对ListView中的每一个item视图的配置。
